49 song preview
hmcc-global/psalted-2 pull request #60
Opened 2024-01-08 14:33 UTC by cetair

2024-01-10 02:06 UTC, tamarayustian approved these changes
<img width="276" alt="image" src="https://github.com/hmcc-global/psalted-2/assets/26876443/f815c5b0-9192-4551-8184-4109d4ddc1d5">

i think we should display the time signature too as one of the chips. but maybe need to squeeze the search bars/filters a little more? or shorten some names? can you try play around and see what is best. otherwise, looks good! thanks

2024-01-10 09:08 UTC, cetair commented
it's a bit ugly if i squeeze it, so i'll shorten the name to time instead

2024-01-11 14:29 UTC, Midnite1212 requested changes

2024-01-11 14:29 UTC, Midnite1212 commented on ui/src/components/song/SongCard.tsx
> +        background: 'secondary.lighter',
I dont think the backgroun is working properly need to change it to specifically backgroundColor
```suggestion
        backgroundColor: 'secondary.lighter',
```

2024-01-18 10:18 UTC, merged