95 login mobile
hmcc-global/psalted-2 pull request #96
Opened 2024-10-18 16:25 UTC by ksuhartono97

mobile view for login page

2024-10-31 15:29 UTC, yuenyauu requested changes
minor ui tweaks, but otherwise lgtm

also, i checked iPad mini view, it seems that the login/register containers are horizontally stacked with the "Welcome to Ripple Worship" heading, i think it shld stack vertically.

for iPad air onwards it's fine to stack horizontally, but iPad mini maybe vertical :)

2024-10-31 15:29 UTC, yuenyauu commented on ui/src/components/auth/LoginContainer.tsx
> +                  REMEMBER ME
nitpicky, but maybe don't CAPS everything :D

2024-10-31 15:29 UTC, yuenyauu commented on ui/src/components/auth/LoginContainer.tsx
>                  FORGOT PASSWORD?
This too

2024-10-31 15:29 UTC, yuenyauu commented on ui/src/components/auth/LoginContainer.tsx
> +                  <Typography variant="subtitle1">SIGN UP</Typography>
This too hehe

2024-10-31 15:29 UTC, yuenyauu commented on ui/src/components/auth/RegisterContainer.tsx
> +                  Full Name
font color doesn't look right? should be secondary.light ? #EADDFF

2024-10-31 15:29 UTC, yuenyauu commented on ui/src/components/auth/RegisterContainer.tsx
> +                <Typography variant="subtitle1">Already have an account? Login</Typography>
Can we split the "Already have an account?" and "Login"? so that Login can be a different color too :D

2024-11-01 07:58 UTC, ksuhartono97 commented
I noticed a weird hover behavior, as such I changed the theme file for SECONDARY_DARK color. Not sure if this causes other issues throughout the site as theming wise it looked fine

2024-11-02 11:05 UTC, yuenyauu approved these changes

2024-11-02 11:05 UTC, merged